### ISSUE TITLE
Increase size of text

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue-jadonk#20]
Reduce number of characters

**Comment by erikwelsh** [comment]
Rev A1 did a bit of this.  Will continue to work on this in Rev A2 and B1.

**Comment by erikwelsh** [comment]
Tried to increase text size as much as possible for A2.  Will leave open for comments about text issues.

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#37
