### ISSUE TITLE
Need spec on conformal coating

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue-jadonk#38]

**Comment by StrawsonDesign** [comment]
MG chemicals 419D Acrylic Conformal Coating was my original suggestion to Embest. However they used Humiseal 1B73 which is an almost identical product and seems to have worked well on our prototypes.

**Comment by jadonk** [comment]
@StrawsonDesign What areas on the A2 layout? Can you mark-up the board PDF?

**Comment by jadonk** [comment]
Graphic added... https://github.com/jadonk/beaglebone-blue/commit/432ebf36c79731519eb745985146eb871d6f98e4 

Now we just need to add related information to the README.md in the MFG directory and we can close this issue.

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#49
