### ISSUE TITLE
eMMC/SD card goes into read only mode

### ISSUE THREAD

**Issue by shreks7** [jadonk/beaglebone-blue-jadonk#51]
It is impossible to use the BBBlue, it always goes into read-only mode whenever there is a write attempt to eMMC or the SD card (32gb). 
It also gives Input/Output error after it goes the read-only file system mode. 

It's a very irritating bug, any fixes? or Is it a hardware issue?

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#40
