### ISSUE TITLE
Beaglebone Blue: Pull PWM Pins Low on Boot

### ISSUE THREAD

**Issue by ansarid** [jadonk/beaglebone-blue-jadonk#53]
Currently we have a large robot that is using the GPS UART-RX and UART-TX as PWM outputs for an H-Bridge that only allows a PWM logic level of 5.5v max (this is why we are not using the on board motor outputs). During boot our PWM pins get pulled high which is an issue because it causes the robot to start moving.

Is there a way to configure pins to stay low on boot to avoid this issue?

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#46
