### ISSUE TITLE
Drivers of the motors are insufficiently protected for over-current

### ISSUE THREAD

**Issue by dorovl** [jadonk/beaglebone-blue-jadonk#54]
According to the datasheet of the TB6612FNG circuit have an output current: IOUT = 1.2 A(ave)/3.2 A (peak) but also a built-in thermal shutdown circuit. I first measured the running (0.2 A) and starting current (1.2 A) of my motors and then connected them to the board.

I tested the motors with "rc_test_motors" program from Robot Control Library and this worked fine. Meanwhile, I also added the "-s {duty}" argument which sweeps motors back and forward at duty cycle. I applied for test a very short duty cycle of level 1, which induced a very high current and the burned-out the driver IC.

In a pernicious way, after the incident, the drivers IC are sinking a very high current (dissipating a lot of heat) which caused a malfunction of the eMMC (read only file system). To continue to operate my BeagleBone, it was necessary to undersold the driver ICs with hot air. However, the conformal coating material was infiltrated between the circuit and the PCB making undersoldering impossible without raising the air hot temperature over 400 °C. This damaged the plastic connectors nearby, but my BeagleBone is still working. 

- **We recommend to use a fast current limiter because it seems that the built-in thermal shutdown circuit has in not fast enough for transient effects over-current protection.**

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#38
