### ISSUE TITLE
The two black JST-SH connectors don't have a retention bed, unlike the white JST-SH connectors

### ISSUE THREAD

**Issue by dorovl** [jadonk/beaglebone-blue-jadonk#55]
The connector that plugs inside is not retained. By vibrations, this connector comes out and this is particularly dangerous in the context of a flight controller (our project).

Please note I'm referring to the "Power out" and "4 ADC" connectors (see red arrow):

![70449422-400f7380-1aa2-11ea-854c-7c430386f376](https://user-images.githubusercontent.com/8594515/70524491-89fd6580-1b45-11ea-817d-c45aecb2ebae.png)

- **We recommend to put also a white JST-SH connectors on the next version.**

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#45
