### ISSUE TITLE
Add PDFs

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-blue-jadonk#9]

**Comment by jadonk** [comment]
Need to automate the generation to stay up-to-date. The OSHPark preview looks really great.

**Comment by silver2row** [comment]
Hello...I see you want help. It is late now but I will have time every now and then. Better late than never.

Seth

P.S. Reply if you still can use someone to assist.

**Comment by jadonk** [comment]
Issue migrated to beagleboard/beaglebone-blue#51
